apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
    editable: true
    isDefault: true
    uid: victoria